//for get mainTypes actions
export const REQUEST_FOR_GET_MAINTYPE_IS_IN_PROGRESS =
  'REQUEST_FOR_GET_MAINTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_GET_MAINTYPE_SUCCESS = 'REQUEST_FOR_GET_MAINTYPE_SUCCESS';
export const REQUEST_FOR_GET_MAINTYPE_ERROR = 'REQUEST_FOR_GET_MAINTYPE_ERROR';

//for post mainTypes actions
export const REQUEST_FOR_ADD_MAINTYPE_IS_IN_PROGRESS =
  'REQUEST_FOR_ADD_MAINTYPE_IS_IN_PROGRESS';
export const REQUEST_FOR_ADD_MAINTYPE_SUCCESS = 'REQUEST_FOR_ADD_MAINTYPE_SUCCESS';
export const REQUEST_FOR_ADD_MAINTYPE_ERROR = 'REQUEST_FOR_ADD_MAINTYPE_ERROR';
